export const gameData = [
  {
    name: "Frost & Flame: King of Avalon",
    slug: "frost-and-flame-king-of-avalon",
    image: "/images/games/frostandflame.webp",
    category: "Strategy & War",
  },
  {
    name: "Guns of Glory: Lost Island",
    slug: "guns-of-glory-lost-island",
    image: "/images/games/gunsofglory.webp",
    category: "Strategy & War",
  },
  {
    name: "Sea of Conquest: Pirate War",
    slug: "sea-of-conquest-pirate-war",
    image: "/images/games/seaofconquest.webp",
    category: "Naval & Adventure",
  },
  {
    name: "State of Survival: Zombie War",
    slug: "state-of-survival-zombie-war",
    image: "/images/games/stateofsurvival.webp",
    category: "Survival & Zombie",
  },
  {
    name: "Whiteout Survival",
    slug: "whiteout-survival",
    image: "/images/games/whiteout.webp",
    category: "Survival & Zombie",
  },
  {
    name: "Kingshot",
    slug: "kingshot",
    image: "/images/games/kingshot.webp",
    category: "Fantasy / RPG",
  },
  {
    name: "Diablo Immortal",
    slug: "diablo-immortal",
    image: "/images/games/diablo.webp",
    category: "Fantasy / RPG",
  },
  {
    name: "Last War: Survival Game",
    slug: "last-war-survival-game",
    image: "/images/games/lastwar.webp",
    category: "Survival & Zombie",
  },
  {
    name: "Last Z: Survival Shooter",
    slug: "last-z-survival-shooter",
    image: "/images/games/lastz.webp",
    category: "Survival & Zombie",
  },
  {
    name: "Misty Continent: Cursed Island",
    slug: "misty-continent-cursed-island",
    image: "/images/games/cursedisland.webp",
    category: "Naval & Adventure",
  },
  {
    name: "The Grand Mafia",
    slug: "the-grand-mafia",
    image: "/images/games/grandmafia.webp",
    category: "Strategy & War",
  },
  {
    name: "Mafia City",
    slug: "mafia-city",
    image: "/images/games/mafiacity.webp",
    category: "Strategy & War",
  },
  {
    name: "Primitive Era: 10000BC",
    slug: "primitive-era-10000bc",
    image: "/images/games/primitiveera.webp",
    category: "Survival & Zombie",
  },
  {
    name: "Evony: The Kings Return",
    slug: "evony-the-kings-return",
    image: "/images/games/kingsreturn.webp",
    category: "Strategy & War",
  },
  {
    name: "Dark War Survival",
    slug: "dark-war-survival",
    image: "/images/games/darkwar.webp",
    category: "Survival & Zombie",
  },
  {
    name: "Call of Dragons",
    slug: "call-of-dragons",
    image: "/images/games/callofdragons.webp",
    category: "Fantasy / RPG",
  },
  {
    name: "Rise of the Kings",
    slug: "rise-of-the-kings",
    image: "/images/games/riseofthekings.webp",
    category: "Strategy & War",
  },
  {
    name: "Total Battle: Strategy Games",
    slug: "total-battle-strategy-games",
    image: "/images/games/totalbattle.webp",
    category: "Strategy & War",
  },
  {
    name: "Doomsday: Last Survivors",
    slug: "doomsday-last-survivors",
    image: "/images/games/doomsday.webp",
    category: "Survival & Zombie",
  },
  {
    name: "DC: Dark Legion",
    slug: "dc-dark-legion",
    image: "/images/games/darklegion.webp",
    category: "Fantasy / RPG",
  },
  {
    name: "Rise of Castles: Ice and Fire",
    slug: "rise-of-castles-ice-and-fire",
    image: "/images/games/riseofcastles.webp",
    category: "Strategy & War",
  },
  {
    name: "Vikings Rise: Valhalla",
    slug: "vikings-rise-valhalla",
    image: "/images/games/vikings.webp",
    category: "Strategy & War",
  },
  {
    name: "Age of Origins",
    slug: "age-of-origins",
    image: "/images/games/ageoforigins.webp",
    category: "Survival & Zombie",
  },
  {
    name: "War and Order",
    slug: "war-and-order",
    image: "/images/games/warandorder.webp",
    category: "Strategy & War",
  },
  {
    name: "Warpath: Ace Shooter",
    slug: "warpath-ace-shooter",
    image: "/images/games/warpath.webp",
    category: "Shooter / Military",
  },
  {
    name: "Last Fortress: Underground",
    slug: "last-fortress-underground",
    image: "/images/games/lastfortress.webp",
    category: "Survival & Zombie",
  },
  {
    name: "Top War: Battle Game",
    slug: "top-war-battle-game",
    image: "/images/games/topwar.webp",
    category: "Strategy & War",
  },
  {
    name: "Age of Empires Mobile",
    slug: "age-of-empires-mobile",
    image: "/images/games/ageofempires.webp",
    category: "Strategy & War",
  },
  {
    name: "Avatar: Realms Collide",
    slug: "avatar-realms-collide",
    image: "/images/games/avatar.webp",
    category: "Fantasy / RPG",
  },
  {
    name: "Lands of Jail",
    slug: "lands-of-jail",
    image: "/images/games/landsofjail.webp",
    category: "Strategy & War",
  },
];
